// Code generated by protoc-gen-go.
// source: sessionmanagement.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	sessionmanagement.proto

It has these top-level messages:
	Session
	CreateSessionRequest
	CreateSessionReply
	FindSessionByTokenRequest
	FindSessionByTokenReply
	DeleteSessionByTokenRequest
	DeleteSessionByTokenReply
	DeleteSessionsByOwnerTokenRequest
	DeleteSessionsByOwnerTokenReply
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Session struct {
	Created    *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=created" json:"created,omitempty"`
	ValidTo    *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=valid_to,json=validTo" json:"valid_to,omitempty"`
	Token      string                     `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
	OwnerToken string                     `protobuf:"bytes,4,opt,name=owner_token,json=ownerToken" json:"owner_token,omitempty"`
	Agent      string                     `protobuf:"bytes,5,opt,name=agent" json:"agent,omitempty"`
	Ip         string                     `protobuf:"bytes,6,opt,name=ip" json:"ip,omitempty"`
	Policies   []string                   `protobuf:"bytes,7,rep,name=policies" json:"policies,omitempty"`
	Payload    []byte                     `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *Session) Reset()                    { *m = Session{} }
func (m *Session) String() string            { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()               {}
func (*Session) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Session) GetCreated() *google_protobuf.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Session) GetValidTo() *google_protobuf.Timestamp {
	if m != nil {
		return m.ValidTo
	}
	return nil
}

type CreateSessionRequest struct {
	Session *Session `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
}

func (m *CreateSessionRequest) Reset()                    { *m = CreateSessionRequest{} }
func (m *CreateSessionRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateSessionRequest) ProtoMessage()               {}
func (*CreateSessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateSessionRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

type CreateSessionReply struct {
	Session *Session `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Err     string   `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *CreateSessionReply) Reset()                    { *m = CreateSessionReply{} }
func (m *CreateSessionReply) String() string            { return proto.CompactTextString(m) }
func (*CreateSessionReply) ProtoMessage()               {}
func (*CreateSessionReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateSessionReply) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

type FindSessionByTokenRequest struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *FindSessionByTokenRequest) Reset()                    { *m = FindSessionByTokenRequest{} }
func (m *FindSessionByTokenRequest) String() string            { return proto.CompactTextString(m) }
func (*FindSessionByTokenRequest) ProtoMessage()               {}
func (*FindSessionByTokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type FindSessionByTokenReply struct {
	Session *Session `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Err     string   `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *FindSessionByTokenReply) Reset()                    { *m = FindSessionByTokenReply{} }
func (m *FindSessionByTokenReply) String() string            { return proto.CompactTextString(m) }
func (*FindSessionByTokenReply) ProtoMessage()               {}
func (*FindSessionByTokenReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *FindSessionByTokenReply) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

type DeleteSessionByTokenRequest struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *DeleteSessionByTokenRequest) Reset()                    { *m = DeleteSessionByTokenRequest{} }
func (m *DeleteSessionByTokenRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteSessionByTokenRequest) ProtoMessage()               {}
func (*DeleteSessionByTokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type DeleteSessionByTokenReply struct {
	Session *Session `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Err     string   `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *DeleteSessionByTokenReply) Reset()                    { *m = DeleteSessionByTokenReply{} }
func (m *DeleteSessionByTokenReply) String() string            { return proto.CompactTextString(m) }
func (*DeleteSessionByTokenReply) ProtoMessage()               {}
func (*DeleteSessionByTokenReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DeleteSessionByTokenReply) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

type DeleteSessionsByOwnerTokenRequest struct {
	OwnerToken string `protobuf:"bytes,1,opt,name=owner_token,json=ownerToken" json:"owner_token,omitempty"`
}

func (m *DeleteSessionsByOwnerTokenRequest) Reset()         { *m = DeleteSessionsByOwnerTokenRequest{} }
func (m *DeleteSessionsByOwnerTokenRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSessionsByOwnerTokenRequest) ProtoMessage()    {}
func (*DeleteSessionsByOwnerTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{7}
}

type DeleteSessionsByOwnerTokenReply struct {
	Sessions []*Session `protobuf:"bytes,1,rep,name=sessions" json:"sessions,omitempty"`
	Err      string     `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *DeleteSessionsByOwnerTokenReply) Reset()                    { *m = DeleteSessionsByOwnerTokenReply{} }
func (m *DeleteSessionsByOwnerTokenReply) String() string            { return proto.CompactTextString(m) }
func (*DeleteSessionsByOwnerTokenReply) ProtoMessage()               {}
func (*DeleteSessionsByOwnerTokenReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *DeleteSessionsByOwnerTokenReply) GetSessions() []*Session {
	if m != nil {
		return m.Sessions
	}
	return nil
}

func init() {
	proto.RegisterType((*Session)(nil), "pb.Session")
	proto.RegisterType((*CreateSessionRequest)(nil), "pb.CreateSessionRequest")
	proto.RegisterType((*CreateSessionReply)(nil), "pb.CreateSessionReply")
	proto.RegisterType((*FindSessionByTokenRequest)(nil), "pb.FindSessionByTokenRequest")
	proto.RegisterType((*FindSessionByTokenReply)(nil), "pb.FindSessionByTokenReply")
	proto.RegisterType((*DeleteSessionByTokenRequest)(nil), "pb.DeleteSessionByTokenRequest")
	proto.RegisterType((*DeleteSessionByTokenReply)(nil), "pb.DeleteSessionByTokenReply")
	proto.RegisterType((*DeleteSessionsByOwnerTokenRequest)(nil), "pb.DeleteSessionsByOwnerTokenRequest")
	proto.RegisterType((*DeleteSessionsByOwnerTokenReply)(nil), "pb.DeleteSessionsByOwnerTokenReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Sessionmanagement service

type SessionmanagementClient interface {
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionReply, error)
	FindSessionByToken(ctx context.Context, in *FindSessionByTokenRequest, opts ...grpc.CallOption) (*FindSessionByTokenReply, error)
	DeleteSessionByToken(ctx context.Context, in *DeleteSessionByTokenRequest, opts ...grpc.CallOption) (*DeleteSessionByTokenReply, error)
	DeleteSessionsByOwnerToken(ctx context.Context, in *DeleteSessionsByOwnerTokenRequest, opts ...grpc.CallOption) (*DeleteSessionsByOwnerTokenReply, error)
}

type sessionmanagementClient struct {
	cc *grpc.ClientConn
}

func NewSessionmanagementClient(cc *grpc.ClientConn) SessionmanagementClient {
	return &sessionmanagementClient{cc}
}

func (c *sessionmanagementClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionReply, error) {
	out := new(CreateSessionReply)
	err := grpc.Invoke(ctx, "/pb.Sessionmanagement/CreateSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionmanagementClient) FindSessionByToken(ctx context.Context, in *FindSessionByTokenRequest, opts ...grpc.CallOption) (*FindSessionByTokenReply, error) {
	out := new(FindSessionByTokenReply)
	err := grpc.Invoke(ctx, "/pb.Sessionmanagement/FindSessionByToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionmanagementClient) DeleteSessionByToken(ctx context.Context, in *DeleteSessionByTokenRequest, opts ...grpc.CallOption) (*DeleteSessionByTokenReply, error) {
	out := new(DeleteSessionByTokenReply)
	err := grpc.Invoke(ctx, "/pb.Sessionmanagement/DeleteSessionByToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionmanagementClient) DeleteSessionsByOwnerToken(ctx context.Context, in *DeleteSessionsByOwnerTokenRequest, opts ...grpc.CallOption) (*DeleteSessionsByOwnerTokenReply, error) {
	out := new(DeleteSessionsByOwnerTokenReply)
	err := grpc.Invoke(ctx, "/pb.Sessionmanagement/DeleteSessionsByOwnerToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Sessionmanagement service

type SessionmanagementServer interface {
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionReply, error)
	FindSessionByToken(context.Context, *FindSessionByTokenRequest) (*FindSessionByTokenReply, error)
	DeleteSessionByToken(context.Context, *DeleteSessionByTokenRequest) (*DeleteSessionByTokenReply, error)
	DeleteSessionsByOwnerToken(context.Context, *DeleteSessionsByOwnerTokenRequest) (*DeleteSessionsByOwnerTokenReply, error)
}

func RegisterSessionmanagementServer(s *grpc.Server, srv SessionmanagementServer) {
	s.RegisterService(&_Sessionmanagement_serviceDesc, srv)
}

func _Sessionmanagement_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionmanagementServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Sessionmanagement/CreateSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionmanagementServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessionmanagement_FindSessionByToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindSessionByTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionmanagementServer).FindSessionByToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Sessionmanagement/FindSessionByToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionmanagementServer).FindSessionByToken(ctx, req.(*FindSessionByTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessionmanagement_DeleteSessionByToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionByTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionmanagementServer).DeleteSessionByToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Sessionmanagement/DeleteSessionByToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionmanagementServer).DeleteSessionByToken(ctx, req.(*DeleteSessionByTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessionmanagement_DeleteSessionsByOwnerToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionsByOwnerTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionmanagementServer).DeleteSessionsByOwnerToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Sessionmanagement/DeleteSessionsByOwnerToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionmanagementServer).DeleteSessionsByOwnerToken(ctx, req.(*DeleteSessionsByOwnerTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sessionmanagement_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Sessionmanagement",
	HandlerType: (*SessionmanagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _Sessionmanagement_CreateSession_Handler,
		},
		{
			MethodName: "FindSessionByToken",
			Handler:    _Sessionmanagement_FindSessionByToken_Handler,
		},
		{
			MethodName: "DeleteSessionByToken",
			Handler:    _Sessionmanagement_DeleteSessionByToken_Handler,
		},
		{
			MethodName: "DeleteSessionsByOwnerToken",
			Handler:    _Sessionmanagement_DeleteSessionsByOwnerToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("sessionmanagement.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 465 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xc5, 0x0e, 0xa9, 0x93, 0x09, 0x20, 0x18, 0x45, 0x74, 0xeb, 0xaa, 0x8a, 0x31, 0xaa, 0xc8,
	0xc9, 0x15, 0x2d, 0x1c, 0xb9, 0xb4, 0x15, 0x37, 0x84, 0xe4, 0xe6, 0xc0, 0x01, 0xa9, 0x72, 0x9a,
	0x21, 0x32, 0x38, 0xde, 0xc5, 0xbb, 0x05, 0xf9, 0x13, 0xf8, 0x5d, 0xbe, 0x00, 0x79, 0xd7, 0x6b,
	0x51, 0xc7, 0x6e, 0x2b, 0xf5, 0xe6, 0xd9, 0x79, 0x6f, 0xfc, 0xf6, 0xcd, 0xb3, 0x61, 0x57, 0x92,
	0x94, 0x29, 0xcf, 0x37, 0x49, 0x9e, 0xac, 0x69, 0x43, 0xb9, 0x8a, 0x44, 0xc1, 0x15, 0x47, 0x57,
	0x2c, 0xfd, 0xd9, 0x9a, 0xf3, 0x75, 0x46, 0x47, 0xfa, 0x64, 0x79, 0xfd, 0xed, 0x48, 0xa5, 0x1b,
	0x92, 0x2a, 0xd9, 0x08, 0x03, 0x0a, 0xff, 0xb8, 0xe0, 0x5d, 0x98, 0x01, 0xf8, 0x0e, 0xbc, 0xab,
	0x82, 0x12, 0x45, 0x2b, 0xe6, 0x04, 0xce, 0x7c, 0x72, 0xec, 0x47, 0x86, 0x1e, 0x59, 0x7a, 0xb4,
	0xb0, 0xf4, 0xd8, 0x42, 0xf1, 0x3d, 0x8c, 0x7e, 0x25, 0x59, 0xba, 0xba, 0x54, 0x9c, 0xb9, 0x77,
	0xd3, 0x34, 0x76, 0xc1, 0x71, 0x0a, 0x43, 0xc5, 0x7f, 0x50, 0xce, 0x06, 0x81, 0x33, 0x1f, 0xc7,
	0xa6, 0xc0, 0x19, 0x4c, 0xf8, 0xef, 0x9c, 0x8a, 0x4b, 0xd3, 0x7b, 0xac, 0x7b, 0xa0, 0x8f, 0x16,
	0x1a, 0x30, 0x85, 0x61, 0xb2, 0xa6, 0x5c, 0xb1, 0xa1, 0xa1, 0xe9, 0x02, 0x9f, 0x81, 0x9b, 0x0a,
	0xb6, 0xa3, 0x8f, 0xdc, 0x54, 0xa0, 0x0f, 0x23, 0xc1, 0xb3, 0xf4, 0x2a, 0x25, 0xc9, 0xbc, 0x60,
	0x30, 0x1f, 0xc7, 0x4d, 0x8d, 0x0c, 0x3c, 0x91, 0x94, 0x19, 0x4f, 0x56, 0x6c, 0x14, 0x38, 0xf3,
	0x27, 0xb1, 0x2d, 0xc3, 0x0f, 0x30, 0x3d, 0xd3, 0x97, 0xaa, 0x0d, 0x89, 0xe9, 0xe7, 0x35, 0x49,
	0x85, 0x87, 0xe0, 0xd5, 0x1e, 0xd7, 0xbe, 0x4c, 0x22, 0xb1, 0x8c, 0x2c, 0xc8, 0xf6, 0xc2, 0x4f,
	0x80, 0x2d, 0xba, 0xc8, 0xca, 0x7b, 0x92, 0xf1, 0x39, 0x0c, 0xa8, 0x28, 0xb4, 0x81, 0xe3, 0xb8,
	0x7a, 0x0c, 0xdf, 0xc2, 0xde, 0xc7, 0x34, 0x5f, 0xd5, 0xc8, 0xd3, 0x52, 0xdf, 0xdf, 0x4a, 0x6a,
	0xdc, 0x73, 0xfe, 0x73, 0x2f, 0x8c, 0x61, 0xb7, 0x8b, 0xf2, 0x20, 0x19, 0x27, 0xb0, 0x7f, 0x4e,
	0x19, 0x35, 0xb7, 0xba, 0x97, 0x90, 0x05, 0xec, 0x75, 0x93, 0x1e, 0x24, 0xe5, 0x1c, 0x5e, 0xdd,
	0x98, 0x2a, 0x4f, 0xcb, 0xcf, 0x4d, 0x32, 0xac, 0xa0, 0x56, 0x82, 0x9c, 0x76, 0x82, 0xc2, 0xaf,
	0x30, 0xbb, 0x6d, 0x4a, 0xa5, 0xf0, 0x0d, 0x8c, 0x6a, 0x15, 0x92, 0x39, 0xc1, 0xa0, 0x2d, 0xb1,
	0x69, 0x6e, 0x6b, 0x3c, 0xfe, 0xeb, 0xc2, 0x8b, 0x8b, 0xf6, 0x07, 0x89, 0x67, 0xf0, 0xf4, 0x46,
	0x34, 0x90, 0x55, 0xf3, 0xba, 0xc2, 0xe6, 0xbf, 0xec, 0xe8, 0x88, 0xac, 0x0c, 0x1f, 0x61, 0x0c,
	0xb8, 0xbd, 0x5d, 0x3c, 0xa8, 0xf0, 0xbd, 0x41, 0xf1, 0xf7, 0xfb, 0xda, 0x66, 0xe6, 0x17, 0x98,
	0x76, 0x2d, 0x0a, 0x67, 0x15, 0xed, 0x96, 0xbd, 0xfb, 0x07, 0xfd, 0x00, 0x33, 0xf9, 0x3b, 0xf8,
	0xfd, 0x36, 0xe3, 0xe1, 0x16, 0xbd, 0x6b, 0x99, 0xfe, 0xeb, 0xbb, 0x60, 0xfa, 0x5d, 0xcb, 0x1d,
	0xfd, 0xa3, 0x39, 0xf9, 0x17, 0x00, 0x00, 0xff, 0xff, 0x3e, 0x6a, 0x77, 0xa2, 0x0b, 0x05, 0x00,
	0x00,
}
